name: PorpidPostproc
dependencies:
  - snakemake-minimal
  - pandas
  - jinja2
  - networkx
  - pygraphviz
  - pygments
  - imagemagick
  - boto
  - moto
  - filechunkio
  - pysftp
  - requests
  - ftputil
  - XRootD
  - matplotlib
  - seaborn
  - julia=1.10.5
